/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {

    public static void main(String[] args) {
        new Mobile().call("Hello world.");
        new Iphone().call("Hello world.");
        new Andriod().call("Hello world.");
        Mobile mobile = new Andriod("pro", "blue", "OnePlus");
        System.out.println(mobile);
        Preson preson = new Preson("panda",mobile);
        preson.getMobile().call("Hello world.Hello world.Hello world.");
//        IphoneRobot iphoneRobot = new IphoneRobot(mobile);
    }
}
